export default {
  model:
    "gASVwgoAAAAAAAB9lCiMBW1vZGVslIwUc2tsZWFybi5zdm0uX2NsYXNzZXOUjANTVkOUk5QpgZR9lCiMF2RlY2lzaW9uX2Z1bmN0aW9uX3NoYXBllIwDb3ZylIwKYnJlYWtfdGllc5SJjAZrZXJuZWyUjAZsaW5lYXKUjAZkZWdyZWWUSwOMBWdhbW1hlIwFc2NhbGWUjAVjb2VmMJRHAAAAAAAAAACMA3RvbJRHP1BiTdLxqfyMAUOUSwGMAm51lEcAAAAAAAAAAIwHZXBzaWxvbpRHAAAAAAAAAACMCXNocmlua2luZ5SIjAtwcm9iYWJpbGl0eZSJjApjYWNoZV9zaXpllEvIjAxjbGFzc193ZWlnaHSUTowHdmVyYm9zZZSJjAhtYXhfaXRlcpRK/////4wMcmFuZG9tX3N0YXRllE6MB19zcGFyc2WUiYwNY2xhc3Nfd2VpZ2h0X5SMFW51bXB5LmNvcmUubXVsdGlhcnJheZSMDF9yZWNvbnN0cnVjdJSTlIwFbnVtcHmUjAduZGFycmF5lJOUSwCFlEMBYpSHlFKUKEsBSwOFlGggjAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDGAAAAAAAAPA/AAAAAAAA8D8AAAAAAADwP5R0lGKMCGNsYXNzZXNflGgfaCJLAIWUaCSHlFKUKEsBSwOFlGgpjAJpOJSJiIeUUpQoSwNoLU5OTkr/////Sv////9LAHSUYolDGAAAAAAAAAAAAQAAAAAAAAACAAAAAAAAAJR0lGKMBl9nYW1tYZRoHYwGc2NhbGFylJOUaCxDCHcqXCVHbbA/lIaUUpSMCHN1cHBvcnRflGgfaCJLAIWUaCSHlFKUKEsBSxuFlGgpjAJpNJSJiIeUUpQoSwNoLU5OTkr/////Sv////9LAHSUYolDbBcAAAAYAAAAKQAAADQAAAA4AAAAPwAAAEIAAABEAAAARgAAAEgAAABMAAAATQAAAFMAAABUAAAAYgAAAGoAAABuAAAAdwAAAHsAAAB+AAAAfwAAAIEAAACFAAAAigAAAJIAAACTAAAAlQAAAJR0lGKMEHN1cHBvcnRfdmVjdG9yc1+UaB9oIksAhZRoJIeUUpQoSwFLG0sEhpRoLIlCYAMAAGZmZmZmZhRAZmZmZmZmCkAzMzMzMzP7PwAAAAAAAOA/MzMzMzMzE0AzMzMzMzMLQGZmZmZmZv4/mpmZmZmZyT8AAAAAAAASQGZmZmZmZgJAzczMzMzM9D8zMzMzMzPTP5qZmZmZmRtAzczMzMzMCECamZmZmZkTQAAAAAAAAPg/MzMzMzMzGUBmZmZmZmYKQM3MzMzMzBJAmpmZmZmZ+T9mZmZmZmYYQDMzMzMzMwdAzczMzMzMEkBmZmZmZmb2P2ZmZmZmZhZAAAAAAAAACEAAAAAAAAASQAAAAAAAAPg/zczMzMzMGECamZmZmZkBQAAAAAAAABJAAAAAAAAA+D+amZmZmZkXQJqZmZmZmQlAMzMzMzMzE0DNzMzMzMz8PzMzMzMzMxlAAAAAAAAABECamZmZmZkTQAAAAAAAAPg/MzMzMzMzG0BmZmZmZmYGQDMzMzMzMxNAZmZmZmZm9j/NzMzMzMwaQAAAAAAAAAhAAAAAAAAAFEAzMzMzMzP7PwAAAAAAABhAmpmZmZmZBUBmZmZmZmYUQJqZmZmZmfk/mpmZmZmZFUAAAAAAAAAIQAAAAAAAABJAAAAAAAAA+D9mZmZmZmYUQAAAAAAAAARAAAAAAAAACECamZmZmZnxP5qZmZmZmRNAAAAAAAAABEAAAAAAAAASQDMzMzMzM/s/AAAAAAAAGkCamZmZmZkJQGZmZmZmZhRAAAAAAAAAAEAAAAAAAAAYQJqZmZmZmQFAAAAAAAAAFEAAAAAAAAD4PzMzMzMzMxlAmpmZmZmZBUCamZmZmZkTQM3MzMzMzPw/zczMzMzMGEBmZmZmZmYGQDMzMzMzMxNAzczMzMzM/D9mZmZmZmYYQAAAAAAAAAhAmpmZmZmZE0DNzMzMzMz8P83MzMzMzBxAAAAAAAAACEAzMzMzMzMXQJqZmZmZmfk/MzMzMzMzGUBmZmZmZmYGQGZmZmZmZhRAAAAAAAAA+D8AAAAAAAAYQAAAAAAAAAhAMzMzMzMzE0DNzMzMzMz8PzMzMzMzMxlAAAAAAAAABEAAAAAAAAAUQGZmZmZmZv4/AAAAAAAAGkAAAAAAAAAIQM3MzMzMzBRAAAAAAAAAAECamZmZmZkXQAAAAAAAAAhAZmZmZmZmFEDNzMzMzMz8P5R0lGKMCl9uX3N1cHBvcnSUaB9oIksAhZRoJIeUUpQoSwFLA4WUaEmJQwwDAAAADAAAAAwAAACUdJRijApkdWFsX2NvZWZflGgfaCJLAIWUaCSHlFKUKEsBSwJLG4aUaCyJQrABAADxkvLDznblPwAAAAAAAAAAa/S6eaq8sz8AAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAfvEpE2Tu578Ln9KMmBLKvwAAAAAAAACAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIBJuEsjoW+mP/mw/0OwdsQ/AAAAAAAAAAAAAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPzZERZs0I88/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAAAAAAAAAAAADwvwAAAAAAAPC/AAAAAAAA8L8AAAAAAADwvwAAAAAAAPC/AAAAAAAA8L9dLH0v5QXcvwAAAAAAAPC/AAAAAAAA8L9JvIH4s6Tkv1n6Q1qahMS/AAAAAAAA8L+UdJRijAppbnRlcmNlcHRflGgfaCJLAIWUaCSHlFKUKEsBSwOFlGgsiUMYexML39k+9z8XPUbMlx/4P/yqDOm2HxtAlHSUYowGcHJvYkFflGgfaCJLAIWUaCSHlFKUKEsBSwCFlGgsiUMAlHSUYowGcHJvYkJflGgfaCJLAIWUaCSHlFKUKEsBSwCFlGgsiWhudJRijAtmaXRfc3RhdHVzX5RLAIwKc2hhcGVfZml0X5RLlksEhpSMC19pbnRlcmNlcHRflGgfaCJLAIWUaCSHlFKUKEsBSwOFlGgsiUMYexML39k+9z8XPUbMlx/4P/yqDOm2HxtAlHSUYowLX2R1YWxfY29lZl+UaF6MEF9za2xlYXJuX3ZlcnNpb26UjAQwLjIylHVijAdjbGFzc2VzlGgfaCJLAIWUaCSHlFKUKEsBSwOFlGgpjANVMTCUiYiHlFKUKEsDaC1OTk5LKEsESwh0lGKJQ3hzAAAAZQAAAHQAAABvAAAAcwAAAGEAAAAAAAAAAAAAAAAAAAAAAAAAdgAAAGUAAAByAAAAcwAAAGkAAABjAAAAbwAAAGwAAABvAAAAcgAAAHYAAABpAAAAcgAAAGcAAABpAAAAbgAAAGkAAABjAAAAYQAAAAAAAACUdJRidS4=",
  modelInputs: [
    {
      id: "sepal-length",
      val: null,
      name: "Sepal Length (cm)",
      inputType: "number",
    },
    {
      id: "sepal-width",
      val: null,
      name: "Sepal Width (cm)",
      inputType: "number",
    },
    {
      id: "petal-length",
      val: null,
      name: "Petal Length (cm)",
      inputType: "number",
    },
    {
      id: "petal-width",
      val: null,
      name: "Petal Width (cm)",
      inputType: "number",
    },
  ],
  packages: ["scikit-learn"],
  imports: `
    import base64
    import pickle
    from sklearn.svm import SVC
    `,
  async executePython(model, paramList) {
    let res = window.pyodide.runPythonAsync(`
          model_encoded = b'${model}'
          model_obj = pickle.loads(base64.b64decode(model_encoded))
          model = model_obj['model']
          classes = model_obj['classes']
          params = ${paramList}
          x = model.predict([params]).tolist()[0]
          classes[x]
        `);
    return res;
  },
};
